== Overview

=== Purpose

This document is intended to define the topic structure in support of WIS data notifications exchange, 
discovery, and access.

The core driver of WTH is data discovery and filtering as part of the WMO Information System (WIS).footnote:[https://community.wmo.int/activity-areas/wmo-information-system-wis]

=== Scope

This document defines the topic-hierarchy used by WIS message brokers to manage message delivery to the respective group of recipients.
All other topic structure specifications are not in scope.

=== Audience

The target stakeholder audiences for this document include (but are not limited to):

* Metadata providers (NCs, DCPCs)
* WIS Global Services (Global Discovery Catalogues (GDCs), Global Brokers (GB), Global Caches (GC), Global Monitoring (GM))
* WIS Nodes
* GAW World Data Centres (WDCs)
* Metadata implementors (generation, ingest)

== Terms and definitions

The following terms and definitions also apply.

=== Abbreviated terms

.Symbols and abbreviated terms
|===
|Abbreviation |Term

|API
|Application Programming Interface

|DCPC
|Data Collection and Production Centres

|GDC
|Global Discovery Catalogue

|GIS
|Geographic Information System

|GISC
|Global Information System Centre

|HTML
|Hypertext Markup Language

|HTTP
|Hypertext Transfer Protocol

|HTTPS
|Hypertext Transfer Protocol Secure

|IANA
|Internet Assigned Numbers Authority

|IETF
|Internet Engineering Task Force
 
|ISO
|International Organization for Standardization

|JSON
|JavaScript Object Notation

|MQP
|Message queuing protocol

|MQTT
|Message Queuing Telemetry Transport

|NC
|National Centre

|NWP
|Numerical Weather Prediction

|OGC
|Open Geospatial Consortium

|REST
|Representational State Transfer

|TT-WISMD
|Task Team on WIS Metadata

|URI
|Uniform Resource Identifier

|URL
|Uniform Resource Locator

|W3C
|World Wide Web Consortium

|WCMP
|WMO Core Metadata Profile

|WIS
|WMO Information System

|WMO
|World Meteorological Organization

|WTH
|WIS Topic Hierarchy
|===

== Conventions

=== Publication

The WTH can be found at TODO (URL to deployment)

== The WIS Topic Hierarchy

The WIS Topic Hierarchy (WTH) provides a structure used by data providers and WIS Global Services in support of core WIS workflows: publish, discover, subscribe and download.

=== Real-time data sharing

WIS real-time data sharing is based on a message queuing protocol (MQP) supporting a publication/subscription mechanism. A user can subscribe to an MQP broker to receive real-time notifications. The notifications can be sent for new or updated data, for metadata, or also for reports. The notification message received from the MQP broker contains a URL to download the data. The MQP broker offers a range of topics organised in a hierarchy. The users can select their topics of interest and subscribe to them to receive notifications and download data relevant to their work.

=== Data discovery

Users can discover datasets from the Global Discovery Catalogue (GDC). Once a user has identified a dataset of interest, they may subscribe to data notifications and updates using the topic and MQP broker found from the GDC dataset discovery metadata. Datasets in the GDC are made available via the WMO Core Metadata Profile 2 (WCMP2) standard for discovery metadata, which supports a categorisation scheme consistent with the topic hierarchy to provide a seamless search experience compatible with the access modality provided by the MQP broker. In other words, the MQP topic and WIS discovery metadata have the same vocabulary so that discovery, subscription, and download are consistent.

=== Structure

The structure of the topic hierarchy underpins the discovery and sharing of data in WIS, and it has to be standardized across all the WIS services to provide consistent search and access to the user.

Recalling that WIS is designed to support the WMO Unified Data Policy, the topic hierarchy must be aligned with WMO Res. 1 Cg-EXT-21 - Unified Data Policy.:footnote:[https://ane4bf-datap1.s3-eu-west-1.amazonaws.com/wmocms/s3fs-public/ckeditor/files/Cg-Ext2021-d04-1-WMO-UNIFIED-POLICY-FOR-THE-INTERNATIONAL-approved_en_0.pdf?4pv38FtU6R4fDNtwqOxjBCndLIfntWeR]

The WIS Topic Hierarchy has been developed according to the classification of the Earth System domains in Annex 1 of Resolution 1 Cg-Ext(2021), and it is managed in two parts:

1. Primary topic levels (levels 1-8): topic structure applies to all data and services in WIS and is managed by the WMO Secretariat
2. Domain-specific topic subcategory levels (level 9 and beyond): topic structure proposed by domain experts and user communities. Note that the number of levels in this part may vary according to the requirements of various domains.

== Management

The WTH is managed by the WMO Task Team on WIS Metadata. Updates to the WTH are made as part of two workflows: core levels, and domain specific levels.

=== Responsibility

==== Core levels

WTH core levels (1-8) are managed by the WMO Task Team on WIS Metadata.

==== Domain specific levels

WTH domain specific levels (level 9 and beyond) are determined by various teams familiar with the given domain.

=== Managing updates

==== Domain specific levels

WTH domain specific levels are updated using the following steps:

- domain specific teams submit proposals to TT-WISMD
- TT-WISMD performs a review of the proposal and curates the content for consistency.  Discussion and clarifications on the proposal are performed as required
- once consensus is reached, TT-WISMD approves the proposal for inclusion into the next release of WTH
- Final approval of the WTH updates will go through the WMO fast-track amendment process.footnote:[https://community.wmo.int/en/activity-areas/wis/amendment-processes-wis-manuals-and-guides]

=== Versioning

TODO

== Reference implementation

The TT-WISMD maintains pywcmpfootnote:[https://github.com/wmo-im/pywcmp], as the
reference WTH validation utility which includes:

* validation of topics against this specification
* browsing topics at a given level

Documentation on installation, configuration and usage can be found on the
pywcmp website.

pywcmp is provided as a resource to the community, under continuous
improvement. Contributions are welcome and can be facilited by the
WMO Task Team on WIS Metadata.
