== The WIS2 Topic Hierarchy

The WIS Topic Hierarchy (WTH) provides a structure used by data providers and WIS Global Services in support of core WIS workflows: publish, discover, subscribe and download.

The standard topic structure ensures that the WIS2 ecosystem (data publisher, data user, and global services) is a robust, effective, and unified data exchange platform for weather, climate, and water.

The WTH is a simple text string of topics separated by a "/" and it is used to categorize notifications for real-time/near-real-time data, metadata records and reports. For example, [...data/weather/surface-based-observations...].

=== Conformance Class Core

==== Overview

This Core Conformance Class provides requirements for the definition and management of the WIS2 Topic Hierarchy.

include::../requirements/requirements_class_core.adoc[]

//add description on the types of levels and numbers of levels here

The table below provides an overview primary topic levels of the WIS2 topic hierarchy.

.WTH primary topic levels
|===
|Level|Name|Description

|1
|channel
|Location of where the data originates from (data providers [origin] or global services [cache])

|2
|version
|Alphabetical version of the topic hierarchy

|3
|system
|Fixed value of ``wis2`` for WIS2

|4
|centre-id
|Acronym as specified by member and endorsed by the PR of the country and WMO

|5
|notification-type
|WIS2 notification types (``data``, ``metadata``, or ``reports`` [from monitoring activities])

|6
|data-policy
|Data policy as defined by the WMO Unified Data Policy. ``core`` data are available with open access on a free and unrestricted basis and ``recommended`` data are available from the original NC/DCPC which may require authentication or authorization

|7
|earth-system-discipline
|Seven high-level categories as defined by the WMO Unified Data Policy, Annex 1: (``atmospheric-composition``, ``climate``, ``cryosphere``, ``hydrology``, ``ocean``, ``space-weather``, or ``weather``)

|===


==== Management
{{_I think these two paragraphs belong in the introduction_}}

The WTH is managed by the WMO. Updates to the WTH are made as part of two workflows: primary levels and sub-discipline specific levels.

1. Primary topic levels (levels 1-7): topic structure applies to all data and services in WIS.  They are relational, meaning that any combination of each level can be used to construct a topic applicable to a data or metadata notification
2. Sub-discipline topics (level 8 and beyond): topic structures proposed by domain experts and user communities.  These levels are a hierarchical representation of the dataset and the number of levels in this part may vary according to the requirements of various domains.

include::../requirements/core/REQ_management.adoc[]
include::../requirements/core/REQ_releasing.adoc[]

==== Versioning

The topic hierarchy version helps data providers and data consumers with change management and transition in relation to updates.

include::../requirements/core/REQ_versioning.adoc[]

==== Conventions

All levels of the topic hierarchy are defined in a consistent manner to support a normalized and predictable structure.

include::../requirements/core/REQ_conventions.adoc[]

==== Centre identification

The centre identifier (``centre-id``) is an acronym as specified by the member and endorsed by the PR of the country and WMO.  It is a single identifier comprised of a top-level domain (TLD) and centre name. It represents the data publisher, distributor or issuing centre of a given dataset, data product, data granule or other resource.

include::../requirements/core/REQ_centre-id.adoc[]
include::../recommendations/core/REC_centre-id.adoc[]
include::../recommendations/core/PER_centre-id.adoc[]

==== Publishing guidelines

For maximum utility and efficient management of topics, it is recommended that ``data``, ``metadata``, and ``reports`` need to be published to a detailed level. This helps with avoiding "pollution" of messages in higher level topics which are used to delineate core concepts (centre identification, notification types, data policy, etc.).  Note that each discpline has a sub-discipline topic named ``experimental`` for publication to provisional topics.

include::../requirements/core/REQ_publishing.adoc[]
include::../recommendations/core/REC_publishing.adoc[]
include::../recommendations/core/PER_publishing.adoc[]
