name: Publish TTL files to WMO Codes Registry testing environment

env:
  WMO_CODES_TEST_USER_ID: ${{ secrets.CODES_REGISTRY_API_USER_ID }}
  WMO_CODES_TEST_API_KEY: ${{ secrets.CODES_REGISTRY_API_SECRET_TEST }}

on:
  push:
    branches:
      - code-registry-pub-test

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Copy TTL files
        run: |
          mkdir /tmp/wis
          cp -rp wis/ /tmp/
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r scripts/requirements.txt
      - name: create TTL and publish to codes registry
        run: |
          python3 scripts/codeslists2ttl.py
          python3 scripts/upload_changes.py $WMO_CODES_TEST_USER_ID $WMO_CODES_TEST_API_KEY test wis/topic-hierarchy/centre-id/ --status stable
      