name: Publish TTL files to WMO Codes Registry testing environment

env:
  WMO_CODES_TEST_USER_ID: ${{ secrets.WMO_CODES_TEST_USER_ID }}
  WMO_CODES_TEST_API_KEY: ${{ secrets.WMO_CODES_TEST_API_KEY }}

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'wis/**.ttl'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Copy TTL files
        run: |
          mkdir /tmp/wis
          cp -rp wis/ /tmp/
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r scripts/requirements.txt
     # - name: update gh-pages branch and publish
     #   run: |
     #     python3 scripts/upload_changes.py {WMO_CODES_TEST_USER_ID} {WMO_CODES_TEST_API_KEY} test /tmp/wis --status experimental
