name: Publish TTL files to WMO Codes Registry testing environment

env:
  WMO_CODES_TEST_USER_ID: ${{ secrets.CODES_REGISTRY_API_USER_ID }}
  WMO_CODES_TEST_API_KEY: ${{ secrets.CODES_REGISTRY_API_SECRET_TEST }}
  INFOMANIAK_USER: ${{ secrets.INFOMANIAK_SCHEMA_USER }}
  INFOMANIAK_PW: ${{ secrets.INFOMANIAK_SCHEMA_PASSWORD }}

on:
  push:
    branches:
      - code-registry-pub-test


jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r scripts/requirements.txt
      - name: create TTL and publish to codes registry
        run: |
          python3 scripts/codelists2ttl.py
          python3 scripts/upload_changes.py $WMO_CODES_TEST_USER_ID $WMO_CODES_TEST_API_KEY test wis/topic-hierarchy/centre-id/ --status experimental
      - name: create bundle 
        run: |
          python3 scripts/generate-bundle.py
          rm -rf /tmp/wis2-topic-hierarchy-a.zip
          zip -j /tmp/wis2-topic-hierarchy-a.zip topic-hierarchy/*.csv
      - name: upload bundle to Infomaniak
        uses: sozo-design/curl@v1.0.2
        with:
          args: |
            -T /tmp/wis2-topic-hierarchy-a.zip -u "$INFOMANIAK_USER:$INFOMANIAK_PW" ftps://egji.ftp.infomaniak.com/wth/a/wis2-topic-hierarchy-a_test.zip